name: traefik_config_generator_dev

services:
  traefik_config_generator_dev:
    image: alpine/socat
    restart: always
    command: TCP-LISTEN:80,fork TCP:10.1.1.70:3000
    labels:
      traefikConfigGen.port: 5174
      traefikConfigGen.address: traefikdev.jmcdowall.com

